version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/prime_app
permissions:
  - object: /home/ec2-user/prime_app
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
